import { subDays, subMonths } from 'date-fns'

const today = new Date()

// Sample Persons
export const samplePersons = [
  {
    id: 'p1',
    name: 'Ali Rezaei',
    role: 'employee',
    linkedProjectIds: ['kab', 'diba'],
    email: 'ali@example.com',
  },
  {
    id: 'p2',
    name: 'Sara Mohammadi',
    role: 'contractor',
    linkedProjectIds: ['kab'],
    email: 'sara@example.com',
  },
  {
    id: 'p3',
    name: 'Mohammad Karimi',
    role: 'partner',
    linkedProjectIds: ['diba'],
    email: 'mohammad@example.com',
  },
  {
    id: 'p4',
    name: 'Fatemeh Ahmadi',
    role: 'employee',
    linkedProjectIds: ['kab'],
    email: 'fatemeh@example.com',
  },
]

// Sample Transactions
export const sampleTransactions = [
  // Kabinex transactions
  {
    id: 'tx1',
    projectId: 'kab',
    type: 'income',
    kind: 'project',
    money: { amount: 15000000, currency: 'IRR' },
    date: subDays(today, 5).toISOString(),
    category: 'Other',
    description: 'Client invoice - Phase 1',
    personId: null,
    tags: ['invoice', 'phase1'],
  },
  {
    id: 'tx2',
    projectId: 'kab',
    type: 'expense',
    kind: 'project',
    money: { amount: 1000000, currency: 'IRR' },
    date: subDays(today, 10).toISOString(),
    category: 'Software',
    description: 'Paid supplier for tools',
    personId: null,
    tags: ['supplier'],
  },
  {
    id: 'tx3',
    projectId: 'kab',
    type: 'expense',
    kind: 'project',
    money: { amount: 5000000, currency: 'IRR' },
    date: subDays(today, 15).toISOString(),
    category: 'Salary',
    description: 'Monthly salary - Ali Rezaei',
    personId: 'p1',
    commitmentId: 'c1',
    tags: ['salary'],
  },
  {
    id: 'tx4',
    projectId: 'kab',
    type: 'expense',
    kind: 'project',
    money: { amount: 3000000, currency: 'IRR' },
    date: subDays(today, 20).toISOString(),
    category: 'Marketing',
    description: 'Social media ads',
    personId: null,
    tags: ['ads'],
  },
  {
    id: 'tx5',
    projectId: 'kab',
    type: 'income',
    kind: 'project',
    money: { amount: 8000000, currency: 'IRR' },
    date: subDays(today, 25).toISOString(),
    category: 'Other',
    description: 'Client payment - advance',
    personId: null,
    tags: ['advance'],
  },
  // Diba denim transactions
  {
    id: 'tx6',
    projectId: 'diba',
    type: 'income',
    kind: 'project',
    money: { amount: 30000000, currency: 'IRR' },
    date: subDays(today, 3).toISOString(),
    category: 'Other',
    description: 'Main contract payment',
    personId: null,
    tags: ['contract'],
  },
  {
    id: 'tx7',
    projectId: 'diba',
    type: 'expense',
    kind: 'project',
    money: { amount: 15000000, currency: 'IRR' },
    date: subDays(today, 7).toISOString(),
    category: 'Salary',
    description: 'Monthly salary - Mohammad Karimi',
    personId: 'p3',
    commitmentId: 'c2',
    tags: ['salary'],
  },
  {
    id: 'tx8',
    projectId: 'diba',
    type: 'expense',
    kind: 'project',
    money: { amount: 2000000, currency: 'IRR' },
    date: subDays(today, 12).toISOString(),
    category: 'Equipment',
    description: 'Design software license',
    personId: null,
    tags: ['software'],
  },
  {
    id: 'tx9',
    projectId: 'diba',
    type: 'expense',
    kind: 'project',
    money: { amount: 5000000, currency: 'IRR' },
    date: subDays(today, 18).toISOString(),
    category: 'Marketing',
    description: 'Campaign launch',
    personId: null,
    tags: ['campaign'],
  },
  // Personal transactions
  {
    id: 'tx10',
    projectId: null,
    type: 'expense',
    kind: 'personal',
    money: { amount: 2000000, currency: 'IRR' },
    date: subDays(today, 2).toISOString(),
    category: 'Travel',
    description: 'Personal travel',
    personId: null,
    tags: ['personal'],
  },
  {
    id: 'tx11',
    projectId: null,
    type: 'expense',
    kind: 'personal',
    money: { amount: 1500000, currency: 'IRR' },
    date: subDays(today, 8).toISOString(),
    category: 'Office',
    description: 'Home office supplies',
    personId: null,
    tags: ['office'],
  },
]

// Sample Commitments
export const sampleCommitments = [
  {
    id: 'c1',
    projectId: 'kab',
    personId: 'p1',
    label: 'Monthly salary - Ali Rezaei',
    kind: 'recurring',
    money: { amount: 5000000, currency: 'IRR' },
    frequency: 'monthly',
    startDate: subMonths(today, 3).toISOString(),
    endDate: null,
  },
  {
    id: 'c2',
    projectId: 'diba',
    personId: 'p3',
    label: 'Monthly salary - Mohammad Karimi',
    kind: 'recurring',
    money: { amount: 15000000, currency: 'IRR' },
    frequency: 'monthly',
    startDate: subMonths(today, 2).toISOString(),
    endDate: null,
  },
  {
    id: 'c3',
    projectId: 'kab',
    personId: 'p2',
    label: 'Fixed payout for design work',
    kind: 'one_off',
    money: { amount: 10000000, currency: 'IRR' },
    startDate: subDays(today, 30).toISOString(),
    endDate: null,
  },
  {
    id: 'c4',
    projectId: 'kab',
    personId: 'p4',
    label: 'Monthly salary - Fatemeh Ahmadi',
    kind: 'recurring',
    money: { amount: 4000000, currency: 'IRR' },
    frequency: 'monthly',
    startDate: subMonths(today, 1).toISOString(),
    endDate: null,
  },
]

